### ISSUE TITLE
The server is dead

### ISSUE THREAD

**Issue by Darkempire78** [jonathanklee/Sapio#9]
![Screenshot_20221208-200009](https://user-images.githubusercontent.com/50015928/206543883-50713df5-a109-435c-9cbc-b88b433589d0.png)

**Comment by jonathanklee** [comment]
@Darkempire78 yes next release in fdroid should fix it. Otherwise you can build from source.

**Comment by Darkempire78** [comment]
I'm using the v0.11

**Comment by jonathanklee** [comment]
@Darkempire78 Did you recompile it from the source ? Can you try with this apk ? https://ufile.io/8e2rqdzx

**Comment by jonathanklee** [comment]
@Darkempire78 Issue should be fixed. There was an image on the server causing an issue. Issue should be fixed with 0.12.

**Comment by jonathanklee** [comment]
@Darkempire78 Thank you for the report!

**Comment by Relected** [comment]
I'm sorry to break it to you, but I'm using 0.12 and I still have the same problem

**Comment by jonathanklee** [comment]
@Relected Do you still face the issue ? I can see new evaluations in the feed.

**Comment by marcdw1289** [comment]
Server seems to be unreachable again. For several days now.
Installed 0.13 (F-Droid) on two other ROMs to rule out device issues. No connection on any.

**Comment by jonathanklee** [comment]
@marcdw1289 Yes the fix has been released. It's under deployment on Fdroid: 

https://gitlab.com/fdroid/fdroiddata/-/blob/03beb295869585115393bc622b92d22b30984a00/metadata/com.klee.sapio.yml

**Comment by Retardium** [comment]
It's not working since a couple of days: 
![60f23180-160a-4dc3-8062-29ffccf2f965](https://user-images.githubusercontent.com/32235655/221424883-9bdeec51-97b9-4620-93e5-b2a67b75a5e0.png)

**Comment by jonathanklee** [comment]
@Retardium I uploaded the release 18 apk here: https://github.com/jonathanklee/Sapio/releases/tag/v0.18

**Comment by Retardium** [comment]
> 

Thanks, version 0.18 works!
